spring.application.name=sgm

#spring.datasource.url=jdbc:postgresql://localhost/db_sgm
#spring.datasource.username=${POSTGRES_USERNAME}
#spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

backend.security.token.secret=${JWT_SECRET:12345678}

server.port=${PORT:8080}
